### ISSUE TITLE
Hires Blur Emulation missing?

### ISSUE THREAD

**Issue by erictorres101783** [byuu/byuu#24]
Games like Jurassic Park for SNES have transparency but there seems to be no "Hires Blur Emulation" for enabling it. Also, why not call it "Enable Transparency" instead? Just wondering.

**Comment by Screwtapello** [comment]
The SNES supports proper transparency (and other effects) called [color math](https://www.youtube.com/watch?v=zcoU6-9_fDM).  Some games (notably Kirby 3 and Jurassic Park) used the color math hardware for other purposes, so when they wanted a transparency effect, they had to simulate it using hi-res mode. Meanwhile, other games (notably R.P.M. Racing, and the Seiken Densetsu 3 title/menu screen) used hi-res mode for... y'know, high-resolution graphics.

So the option is not called "Enable Transparency" because it doesn't affect the actual SNES transparency effect, but it *does* blur high-resolution graphics. Sometimes that produces a transparency-like effect, sometimes it just makes text blurry.

**Comment by erictorres101783** [comment]
Ok now I understand why it's called "Hires Blur Emulation" so if the option/feature exists in byuu v3 then where is it? Anyway, thanks for the info.

**Comment by byuu** [comment]
It's in the video settings panel.
